//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACCESODATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opiniones
    {
        public int ID_Opinion { get; set; }
        public Nullable<int> ID_Pasajero { get; set; }
        public Nullable<int> ID_Horario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Calificacion { get; set; }
        public string Comentario { get; set; }
    
        public virtual Horarios Horarios { get; set; }
        public virtual Pasajeros Pasajeros { get; set; }
    }
}
